### ISSUE TITLE
flip to start on last view

### ISSUE THREAD

**Issue by aveyD** [ysamlan/horizontalpager#1]
Hi, is there a way when you get to the last view in the list to flip to the first view. or when you are on the first view allow scrolling back to the last view? so you would always be able to scroll left or right past the start/end. Also, is there an easy way to integrate a inflator or something to better allow for custom views?
Great job!

**Comment by aveyD** [comment]
Hi, i figured out a solution to this problem. I'm not sure if its the 100% proper way to do this but this is what i did:
I knew i needed 5 pages for one use of this horizontal pager. What i did was put 5 layouts (which can include images, buttons, etc) in the xml like this: [0, 1, 2, 3, 4], but this only allows scrolling from one end to the other, so i did this in the xml: 
[4, 0, 1, 2, 3, 4, 0]
Then in the onScreenSwitched i say:

if (screen == (numPages+1))
    realViewSwitcher.setCurrentScreen(1, false);
else if (screen == 0)
    realViewSwitcher.setCurrentScreen(numPages, false);

Now it allows for infinitely scrolling through the pages. I also came across a situation where i did not know how many pages i wanted to be able to flip through, so I did something like this:
The xml had 3 layouts wrapped in the HorizontalPager like this: [prev, current, next]. Again, each of these layouts included multiple buttons, images, textViews, etc.
When the user is on the first page (page 0 of N), you set the current screen to 0. Similarly when on the last page (page N) the current screen is set to 2 (the next screen position). Any page in between 0 and N (not including 0 and N) will be set to 1 (the current screen position). When the user swipes or flicks to the next or previous page an update is triggered which will set the current screen back to 1 (current) and update the previous and next values. 

Hope this helps others trying to mimic this behavior.

**Comment by ysamlan** [comment]
That's a good workaround; if this becomes a popular request it probably wouldn't be terribly hard to modify the pager to do this automatically if an "infinite=true" flag is passed in XML or when a setInfinite(true) method is called . If you write it up as a patch (or fork and make a pull request) I'd be happy to include it.
