### ISSUE TITLE
Child View Swipe Events

### ISSUE THREAD

**Issue by ravindranathakila** [ysamlan/horizontalpager#14]
Fix:

```
@Override
public boolean dispatchTouchEvent(MotionEvent ev) {
    getChildAt(0).dispatchTouchEvent(ev);
    this.onTouchEvent(ev);
    return true;
}
```

NOTE: getChildAt uses a magic number.

**Comment by ysamlan** [comment]
This library is obsoleted by Google's release of their own ViewPager library as part of the Android Compatibility Package, revision 3. I would recommend using that for any new development; this library won't be getting any updates or patches.
