### ISSUE TITLE
onConfigurationChanged problem

### ISSUE THREAD

**Issue by aveyD** [ysamlan/horizontalpager#2]
I was having problems with this when the orientation changed. In your example it snaps to the first screen when orientation changes, but i wanted it to snap to the current screen you are on. So what i did was took the snapToScreen code and rather than grabbing the view's getWidth() i substituted the screens width in its place and called the startScroll with duration zero. here is the code to accomplish this:

```
public void orientationSnapToScreen(Context ctx)  
{
Display display = ((WindowManager) ctx.getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay(); 
int displayWidth = display.getWidth();

mNextScreen = Math.max(0, Math.min(getCurrentScreen(), getChildCount() - 1));
    final int newX = mNextScreen * displayWidth;
    final int delta = newX - getScrollX();

    mScroller.startScroll(getScrollX(), 0, delta, 0, 0);
}
```

and then you just call it like this in your code:

```
@ Override

public void onConfigurationChanged(Configuration newConfig)  
{

  super.onConfigurationChanged(newConfig);

  // realViewSwitcher is a HorizontalPager

  realViewSwitcher.orientationSnapToScreen(this);

}
```

Hope this helps :)

**Comment by aveyD** [comment]
problem solved.

**Comment by ysamlan** [comment]
I've wrapped that code into the onMeasure of the pager (there's actually an onConfigurationChanged method for Views in Android 2.2 but to maintain backwards compatibility I've hacked around that by just sniffing for a width change in onMeasure). Thanks!
