### ISSUE TITLE
Empty Space Between Images

### ISSUE THREAD

**Issue by oceanblue22** [ysamlan/horizontalpager#5]
Hi,

I am using the HorizontalPager class to flip from one image to the next. It works great! (Thanks for writing & sharing this)
One problem : There are large empty spaces between images, Not sure if I am doing something wrong or this is a limitation of the code.

This is the scenario I have within the xml:
  <com.github.ysamlan.horizontalpager.HorizontalPager ...>
           <ImageView ... />
           <ImageView ... />
           <ImageView ... />
           <ImageView ... />
  </com.github.ysamlan.horizontalpager.HorizontalPager >

The image pngs are thin & long -  about 18 px (width) X 111 px (height)

Thanks much!

**Comment by ysamlan** [comment]
HorizontalPager is meant only to be used with full-width sublayouts; if your images are 18px wide you're probably better off using a normal Android Gallery. 

If you want those 18px images to be stretched to full width you'll have to define a nine-patch , use an xml-drawable with stretching set, or use the scaleType argument to the ImageView. It's impossible to know what's going on without seeing the layout_width arguments you're using, also.

Maybe I'm just misunderstanding what you're trying to do -- can you show me your layout, an image of what you're expecting to see, and an image of what you're getting instead?

**Comment by oceanblue22** [comment]
Hi Ysamlan,

Thanks for the reply. I did not realise that HorizontalPager is meant to be used with full-width sublayouts. Then the empty spaces do make sense.

I'll close the issue.

**Comment by indsoftdeveloper** [comment]
Hi Ysamlan,
i want to display space between two images in horizontal scrollview when the scroll complete it display in full width for that what changes is required ?
